#!/bin/sh

# A dmenu wrapper script for system functions.

# For non-systemd init systems.
case "$(readlink -f /sbin/init)" in
	*runit*) hib="sudo -A zzz" ;;
	*openrc*) reb="sudo -A openrc-shutdown -r"; shut="sudo -A openrc-shutdown -p" ;;
esac

cmds="\
🔒 lock		slock
🚪 leave qtile	qtile-cmd -o cmd -f shutdown
♻ renew qtile	qtile-cmd -o cmd -f restart
🐻 hibernate	${hib:-sudo -A systemctl suspend-then-hibernate}
🔃 reboot	${reb:-sudo -A reboot}
🖥 shutdown	${shut:-sudo -A shutdown -h now}"

choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu -h 30)" || exit 1

`echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-`
